// <auto-generated />
using BulkyWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BulkyWeb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250816140203_Add50MoreCategories")]
    partial class Add50MoreCategories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BulkyWeb.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Animation"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "Biography"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Name = "Comedy"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            Name = "Crime"
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 7,
                            Name = "Documentary"
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = 8,
                            Name = "Drama"
                        },
                        new
                        {
                            Id = 9,
                            DisplayOrder = 9,
                            Name = "Family"
                        },
                        new
                        {
                            Id = 10,
                            DisplayOrder = 10,
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 11,
                            DisplayOrder = 11,
                            Name = "Film-Noir"
                        },
                        new
                        {
                            Id = 12,
                            DisplayOrder = 12,
                            Name = "History"
                        },
                        new
                        {
                            Id = 13,
                            DisplayOrder = 13,
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 14,
                            DisplayOrder = 14,
                            Name = "Music"
                        },
                        new
                        {
                            Id = 15,
                            DisplayOrder = 15,
                            Name = "Musical"
                        },
                        new
                        {
                            Id = 16,
                            DisplayOrder = 16,
                            Name = "Mystery"
                        },
                        new
                        {
                            Id = 17,
                            DisplayOrder = 17,
                            Name = "Romance"
                        },
                        new
                        {
                            Id = 18,
                            DisplayOrder = 18,
                            Name = "Sci-Fi"
                        },
                        new
                        {
                            Id = 19,
                            DisplayOrder = 19,
                            Name = "Short"
                        },
                        new
                        {
                            Id = 20,
                            DisplayOrder = 20,
                            Name = "Sport"
                        },
                        new
                        {
                            Id = 21,
                            DisplayOrder = 21,
                            Name = "Superhero"
                        },
                        new
                        {
                            Id = 22,
                            DisplayOrder = 22,
                            Name = "Thriller"
                        },
                        new
                        {
                            Id = 23,
                            DisplayOrder = 23,
                            Name = "War"
                        },
                        new
                        {
                            Id = 24,
                            DisplayOrder = 24,
                            Name = "Western"
                        },
                        new
                        {
                            Id = 25,
                            DisplayOrder = 25,
                            Name = "Disaster"
                        },
                        new
                        {
                            Id = 26,
                            DisplayOrder = 26,
                            Name = "Epic"
                        },
                        new
                        {
                            Id = 27,
                            DisplayOrder = 27,
                            Name = "Survival"
                        },
                        new
                        {
                            Id = 28,
                            DisplayOrder = 28,
                            Name = "Psychological"
                        },
                        new
                        {
                            Id = 29,
                            DisplayOrder = 29,
                            Name = "Paranormal"
                        },
                        new
                        {
                            Id = 30,
                            DisplayOrder = 30,
                            Name = "Heist"
                        },
                        new
                        {
                            Id = 31,
                            DisplayOrder = 31,
                            Name = "Spy"
                        },
                        new
                        {
                            Id = 32,
                            DisplayOrder = 32,
                            Name = "Zombie"
                        },
                        new
                        {
                            Id = 33,
                            DisplayOrder = 33,
                            Name = "Christmas"
                        },
                        new
                        {
                            Id = 34,
                            DisplayOrder = 34,
                            Name = "Martial Arts"
                        },
                        new
                        {
                            Id = 35,
                            DisplayOrder = 35,
                            Name = "Time Travel"
                        },
                        new
                        {
                            Id = 36,
                            DisplayOrder = 36,
                            Name = "Space"
                        },
                        new
                        {
                            Id = 37,
                            DisplayOrder = 37,
                            Name = "Alien"
                        },
                        new
                        {
                            Id = 38,
                            DisplayOrder = 38,
                            Name = "Spy Thriller"
                        },
                        new
                        {
                            Id = 39,
                            DisplayOrder = 39,
                            Name = "Legal"
                        },
                        new
                        {
                            Id = 40,
                            DisplayOrder = 40,
                            Name = "Medical"
                        },
                        new
                        {
                            Id = 41,
                            DisplayOrder = 41,
                            Name = "Teen"
                        },
                        new
                        {
                            Id = 42,
                            DisplayOrder = 42,
                            Name = "Political"
                        },
                        new
                        {
                            Id = 43,
                            DisplayOrder = 43,
                            Name = "Road Movie"
                        },
                        new
                        {
                            Id = 44,
                            DisplayOrder = 44,
                            Name = "Coming-of-Age"
                        },
                        new
                        {
                            Id = 45,
                            DisplayOrder = 45,
                            Name = "Satire"
                        },
                        new
                        {
                            Id = 46,
                            DisplayOrder = 46,
                            Name = "Detective"
                        },
                        new
                        {
                            Id = 47,
                            DisplayOrder = 47,
                            Name = "Mockumentary"
                        },
                        new
                        {
                            Id = 48,
                            DisplayOrder = 48,
                            Name = "Found Footage"
                        },
                        new
                        {
                            Id = 49,
                            DisplayOrder = 49,
                            Name = "Game Show"
                        },
                        new
                        {
                            Id = 50,
                            DisplayOrder = 50,
                            Name = "Tragedy"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
